### ISSUE TITLE
Link Menu Underline

### ISSUE THREAD

**Issue by hannespreishuber** [google/material-design-lite#1020]
on http://www.getmdl.io/components/index.html there is the active menu item  underlined. My guess is that it is some magic with Body class=myid and additional class in   <a class="mdl-navigation__link myid"

but that doenst Show expexted result- docu on that? any hint?

**Comment by Garbee** [comment]
It is just some custom styling here is the rule:

```css
.about .docs-navigation .about, .templates .docs-navigation .templates, .started .docs-navigation .started, .styles .docs-navigation .styles, .components .docs-navigation .components, .faq .docs-navigation .faq, .customize .docs-navigation .customize {
    opacity: 1;
    border-bottom-color: #18FFFF;
}
```

So, each page gets its on class on the body. That then will change which item is highlighted based on the selector hit.

Nothing here about what is provided in MDL at the moment. You can use the `--current` modifier on navigation links in your code to get an active state (at least for the drawer.) The primary menu doesn't have a current state it looks like so you'd need to implement this custom.
