### ISSUE TITLE
Striped table

### ISSUE THREAD

**Issue by steren** [google/material-design-lite#1141]
I wish there was a CSS class to display a table with striped rows, like Bootstrap is providing with thw ` `.table-striped` class: http://getbootstrap.com/css/#tables

**Comment by surma** [comment]
AFAIR, there is no striped table in the MD spec, so we won’t add support for it in MDL directly.

However, you can easily add a small style yourself á la
```CSS
.mdl-data-table tbody tr:nth-child(2n) {
  background-color: red;
}
.mdl-data-table tbody tr:nth-child(2n+1) {
  background-color: red;
}
```
