### ISSUE TITLE
Dropdown menu in a layout menu should work without customization

### ISSUE THREAD

**Issue by jimbojetlag** [google/material-design-lite#1154]
Currently we need to specify:

```css
.my-layout__header {
  overflow: visible;
}
```

for the `mdl-layout__header` element. Shouldn't we expect this to work out of the box?
