### ISSUE TITLE
If disabled mdl_textfield has a value it shows this value in enabled color

### ISSUE THREAD

**Issue by MikeMitterer** [google/material-design-lite#1255]
```css
// Styling for the input element.
.mdl-textfield__input {

    .mdl-textfield.is-disabled & {
        background-color: transparent;
        border-bottom: 1px dotted $input-text-disabled-color;
        
        // New
        color: $input-text-label-color;
    }
}
```
![screenshot-1818](https://cloud.githubusercontent.com/assets/116654/8979052/86e29230-36a7-11e5-9758-13b68961660f.png)
