### ISSUE TITLE
Why did you implement drawer_.addEventListener('mousewheel', eatEvent)

### ISSUE THREAD

**Issue by MikeMitterer** [google/material-design-lite#1348]
It makes sense for obfuscator but for Drawer? If the Drawer-contents is higher than your screen size it becomes impossible to scroll via mouse wheel...

https://github.com/google/material-design-lite/blob/master/src/layout/layout.js#l315

**Comment by surma** [comment]
@MikeMitterer Because of #1076. If the drawer is NOT larger than the page, the page scrolls.

I guess I’ll have to come up with another solution.

**Comment by MikeMitterer** [comment]
Hmmm - I can't reproduce it on the MDL/Dart side but when I made my demos I experienced some layout-problems when I added a content to my samples. http://www.material-design-lite.pub/#/layout
I'm using the _eatEvent for obfuscator but not for drawer...
 
Maybe you should test all your layout-samples with content...

I have something like this in my demo.scss:
```css
        .mdl-layout .mdl-layout__content {
            -ms-flex          : 0 1 auto;
            display           : inline-block;
            overflow-y        : scroll;
            overflow-x        : hidden;
            -webkit-box-flex  : 1;
            -webkit-flex-grow : 1;
            -ms-flex-positive : 1;
            flex-grow         : 1;
            z-index           : 1;

            .page-content {
                padding: 8px;

                &:before {
                    content: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et                       dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet                       clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet,                       consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,                       sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.\A\ALorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et                       dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet                       clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet,                       consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,                       sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.\A\ALorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et                       dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet                       clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet,                       consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,                       sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.\A\A";
                    white-space : pre-line;
                }
            }
        }
```
