### ISSUE TITLE
Minification issue with the H5BP file

### ISSUE THREAD

**Issue by Ninir** [google/material-design-lite#1350]
MDL version: 1.0.2
Browser: All
Browser version: -
Operating system: All
Operating system version: -

What steps will reproduce the problem:
1. Get the project
2. Compile it using SCSS
3. Minify the result with uglifycss

URL of a similar problem with YUICSS: https://github.com/h5bp/html5-boilerplate/issues/1315

Compilation tool: Ruby: 2.0.0

Minification tool: UglifyCSS 0.0.15

----

Hello MDL team!

While using the project with sources included, basically importing only needed part of the SCSS for instance, I found a weird issue. The [following lines](https://github.com/google/material-design-lite/blob/master/src/resets/_h5bp.scss#L209-L214) are generated in a weird way when being minified.

This:

```scss
@media print,
       (-o-min-device-pixel-ratio: (5/4)),
       (-webkit-min-device-pixel-ratio: 1.25),
       (min-resolution: 120dpi) {
    /* Style adjustments for high resolution devices */
}

/* ==========================================================================
   Print styles.
   Inlined to avoid the additional HTTP request: h5bp.com/r
   ========================================================================== */

@media print {
```

is minified to this:

```scss
@media print,(-o-min-device-pixel-ratio:5 /@media print{
	*,*:before,*:after{
		background:transparent !important;
		color:#000 !important;
		box-shadow:none !important;
		text-shadow:none !important
	}

	a,a:visited{
		text-decoration:underline
	}

	a[href]:after{
		content:" (" attr(href) ")"
	}

	abbr[title]:after{
		content:" (" attr(title) ")"
	}

	a[href^="#"]:after,a[href^="javascript:"]:after{
		content:""
	}

	pre,blockquote{
		border:1px solid #999;
		page-break-inside:avoid
	}

	thead{
		display:table-header-group
	}

	tr,img{
		page-break-inside:avoid
	}

	img{
		max-width:100% !important
	}

	p,h2,h3{
		orphans:3;
		widows:3
	}

	h2,h3{
		page-break-after:avoid
	}

}
```

You can see the weird first line.

While investigating, I found that uglifyCSS is responsible for this. Deactivating it works well, but there may already have many projects with sources, so...

A potential fix would be to update to the latest H5BP version from the official repository which seem to [have changed the way to set it](https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css#L191-L195), or at least to set the fraction between parenthesis, as in `(-o-min-device-pixel-ratio: (5/4)),`.

The second solution brings a invalid CSS syntax for Opera, which requires a fraction more than a decimal.

What are your thoughts on this?

At the moment, it breaks my application, and I can send a quick PR if you guys agree.

Thanks for your time!
