### ISSUE TITLE
Invalid selector after @supports in progress/_progress.scss

### ISSUE THREAD

**Issue by faviouz** [google/material-design-lite#1485]
I installed MDL through bower. My `main.scss` file looks like this:

```css
@import "../../bower_components/material-design-lite/src/material-design-lite";

/* ... */
```

This is the relevant piece in my `gulpfile.js` that compiles it:

```js
var sass = require('gulp-sass');

gulp.task('styles', function() {
    return gulp.src('./src/styles/main.scss')
        .pipe(sass({
            style: 'expanded',
            precision: 10,
            onError: console.error.bind(console, 'Sass error:')
        }))
        .pipe(gulp.dest(paths.styles.dest));
});
```

The compile errors out like this:

```
Sass error: /vagrant/bower_components/material-design-lite/src/progress/progress:53: error: invalid selector after @supports
```

I can get it to compile if I remove this block of code from `progress/_progress.scss`:

```css
// Webkit only
@supports (-webkit-appearance:none) {
  .mdl-progress:not(.mdl-progress__indeterminate):not(.mdl-progress__indeterminate) > .auxbar {
    background-image: linear-gradient(to right, $progress-secondary-color, $progress-secondary-color),
      linear-gradient(to right, $progress-main-color, $progress-main-color);
    mask: url('/images/buffer.svg?embed');
  }
}
```

What's wrong?
