### ISSUE TITLE
Color overrides

### ISSUE THREAD

**Issue by gauntface** [google/material-design-lite#1533]
Just started to look into why a color override was broken and ultimately it came down to the requirement of needing to copy the format of the color palette variables:

$palette-indigo:
"232,234,246"
"197,202,233"
"159,168,218"
"121,134,203"
"92,107,192"
"63,81,181"
"57,73,171"
"48,63,159"
"40,53,147"
"26,35,126"
"140,158,255"
"83,109,254"
"61,90,254"
"48,79,254";

This was a problem because I was trying to set a primary color like so:

$color-primary: #1F1E24;

Which than produces invalid CSS when the variable for the header color is created like so:

$layout-header-bg-color: unquote("rgb(#{$color-primary})") !default;

Is there any reason not to move the rgb values into the palette arrays themselves? This way a develop can use any color format they desire n the override without things breaking.

**Comment by gauntface** [comment]
In case anyone else is finding the same issues.

For background read this bug:

Possible solution would be to take an approach like this: http://sassmeister.com/gist/a35decd4b14d9e2a37c2

If anyone see's any big issues with this, please comment.

**Comment by tomatau** [comment]
To solve this problem I wrote a utility function and refactored some existing functions by Hugo Giraudel.

Here is an example from my color-definitions.scss file where I take an existing $palette and convert the color string into an actual color object for use within scss.

```scss
$palette-red-50: rgbstring-to-color(nth($palette-red, 1));
```

```scss
// helper for automating unit conversion or error
// to-unit(12, 'px'); /* 12px */
@function to-unit($number, $unit) {
  $strings: 'px' 'cm' 'mm' '%' 'ch' 'pica' 'in' 'em' 'rem' 'pt' 'pc' 'ex' 'vw' 'vh' 'vmin' 'vmax';
  $units:   1px  1cm  1mm  1%  1ch  1pica  1in  1em  1rem  1pt  1pc  1ex  1vw  1vh  1vmin  1vmax;
  $index: index($strings, $unit);
  @if not $index {
    @warn "Unknown unit `#{$unit}`.";
    @return false;
  }
  @return $number * nth($units, $index);
}

/*------------------------------------*\
  TO NUMBER
\*------------------------------------*/
// concerts a string to a number
// to-number("12"); /* returns 12 */
@function to-number($string) {
  $strings: '0' '1' '2' '3' '4' '5' '6' '7' '8' '9';
  $numbers:  0   1   2   3   4   5   6   7   8   9;
  $result: 0;
  $divider: 0;
  $minus: false;
  @for $i from 1 through str-length($string) {
    $character: str-slice($string, $i, $i);
    $index: index($strings, $character);
    @if $character == '-' { $minus: true; }
    @else if $character == '.' { $divider: 1; }
    @else {
      @if not $index {
        $result: if($minus, $result * -1, $result);
        @return to-unit($result, str-slice($string, $i));
      }
      $number: nth($numbers, $index);
      @if $divider == 0 { $result: $result * 10; }
      @else {
        $divider: $divider * 10;
        $number: $number / $divider;
      }
      $result: $result + $number;
    }
  }
  @return if($minus, $result * -1, $result);
}

/*------------------------------------*\
  RGBSTR TO COLOR
\*------------------------------------*/
// given an rgb string, converts to a color
// rgbstr-to-color(123,23,4,0.2); /* returns color object */
@function rgbstring-to-color($rgbString){
  $length: str-length($rgbString);
  $gotRed: false;
  $gotGreen: false;
  $gotBlue: false;
  $red: null;
  $green: null;
  $blue: null;
  $alpha: null;
  @for $i from 1 through $length {
    $token: str-slice($rgbString, $i, $i);
    @if $token == ',' {
      @if $gotRed {
        @if $gotGreen {
          $gotBlue: true;
        } @else {
          $gotGreen: true;
        }
      } @else {
        $gotRed: true;
      }
      // @continue;
    } @else if $token == ' ' {
      // @continue
    } @else {
      @if $gotRed {
        @if $gotGreen {
          @if $gotBlue {
            $alpha: "#{$alpha}#{$token}";
          } @else {
            $blue: "#{$blue}#{$token}";
          }
        } @else {
          $green: "#{$green}#{$token}";
        }
      } @else {
        $red: "#{$red}#{$token}";
      }
    }
  }
  @return rgba(
    to-number($red),
    to-number($green),
    to-number($blue),
    if($alpha, to-number($alpha), 1)
  );
}
```
