### ISSUE TITLE
Bug: Table (Microsoft Edge)

### ISSUE THREAD

**Issue by Shyam-Chen** [google/material-design-lite#1566]
![default](https://cloud.githubusercontent.com/assets/13535256/10261506/c3755616-69cd-11e5-8116-b5bef6e65587.png)

**Comment by Garbee** [comment]
The example [codepen](http://codepen.io/Shyam-Chen/pen/zGeYmb). I don't have Edge handy right now to test against. Will check later once I do.

**Comment by surma** [comment]
I see the same bug in Edge.

**Comment by surma** [comment]
Also, Edge keeps crashing when I open the inspector. We might have another Edge bug here, hard to be sure though.

**Comment by S-YOU** [comment]
making **th** same as **td** seems to be fixed for me.

```css
.mdl-data-table th {
    vertical-align: top;
    padding: 12px 18px 0;
}
```

**Comment by S-YOU** [comment]
making th same as td and removing bottom from select seems to be fixed for me.

http://codepen.io/S-YOU/pen/YyXYyG

```css
.mdl-data-table th {
    vertical-align: top;
    padding: 12px 18px 0;
}
```

`.mdl-data-table th .mdl-data-table__select {`
~~bottom: 8px;~~
`}`
