### ISSUE TITLE
Typography Regression

### ISSUE THREAD

**Issue by brianhall** [google/material-design-lite#227]
Hey there @sgomes, I think the typography change introduced a slight regression:

![](http://f.cl.ly/items/1D3d2X3u3u2G251n2k2v/tMmCTkvZK6.png)

I believe this issue is happening in [_typography.scss](https://github.com/google/material-design-lite/blob/master/src/typography/_typography.scss#L19-L25)

``` css
.mdl-typography {
    html, body {
        font-family: $performance_font;
        font-size: 14px;
        font-weight: 400;
        line-height: 20px;
    }
```

Which outputs:

``` css
.mdl-typography, .mdl-base {
  /**
     * Styles for HTML elements
     */ }
  .mdl-typography html, .mdl-base html, .mdl-typography body, .mdl-base body {
    font-family: 'Helvetica', 'Arial', sans-serif;
    font-size: 14px;
    font-weight: 400;
    line-height: 20px; }
```
