### ISSUE TITLE
Cards / Some "Mobile first" questions

### ISSUE THREAD

**Issue by MikeMitterer** [google/material-design-lite#390]
Why do you have a card-width with 300px defined? Could not find anything related to this in specs?
Makes no sense to me - check out my SS

Cards-Demo:
You have a .demo-card--wide with 600px width. This should check if it is displayed on a small screen. Something like this:

``` css
    .demo-card--wide {
        width: 600px;

        .is-small-screen & {
            width: auto;
        }
    }
```

SS1:
![screenshot-1793](https://cloud.githubusercontent.com/assets/116654/8155591/025b31a4-1346-11e5-8cee-bce938885d55.png)
