### ISSUE TITLE
[DataTable] Why `white-space: nowrap;`?

### ISSUE THREAD

**Issue by tleunen** [google/material-design-lite#4198]
I just noticed the css `white-space: nowrap;` on the datatable. 
https://github.com/google/material-design-lite/blob/master/src/data-table/_data-table.scss#L24

``` css
.mdl-data-table {
  white-space: nowrap;
}
```

Why is this property set?
It forces us to manually reset it because we don't want the `nowrap`.

Can we remove it?
