### ISSUE TITLE
Remove focus ring/outline around drawer button

### ISSUE THREAD

**Issue by leifoolsen** [google/material-design-lite#4290]
MDL version: 1.1.3
Browser: Chrome
Browser version: Latest
Operating system: OSX
Operating system version: Latest

What steps will reproduce the problem:
1. Click on drawer button

What is the expected result?
Focus ring should not be visible

What happens instead of that?
Focus ring is visible

Please provide any other information below, and attach a screenshot if possible.
![screen shot 2016-04-20 at 22 49 11](https://cloud.githubusercontent.com/assets/10088486/14690003/32d554b0-074a-11e6-8977-6f95e515942f.png)

CSS to remove the "annoying" focus ring could be someting like this:

```css
.mdl-layout__drawer-button {

  outline: none;

  // Mozilla, remove focusring
  &:-moz-focusring {
    color: transparent;
    text-shadow: 0 0 0 #000;
  }
}
```
