### ISSUE TITLE
color primary + color ascent

### ISSUE THREAD

**Issue by markopaju** [google/material-design-lite#4301]
Hey,

It would be great if there would be color variations on primary + ascent colors:
mdl-color--primary-50
...
mdl-color--primary-900

mdl-color--accent-50
...
mdl-color--accent-50

If there would be such variations then using the Customize colors wheel ( https://getmdl.io/customize/index.html ) would give us a much wider range of color options.

**Comment by leifoolsen** [comment]
If you use SASS it's relativeley easy to define your own primary an accent colors, e.g:

Your app spesific scheme:
```sass
$mdlapp-text-color-primary: "0,0,0"       !default;
$mdlapp-color-primary: "33,150,243"  !default;
$mdlapp-color-primary-dark: "25,118,210"  !default;
$mdlapp-color-primary-contrast: "255,255,255" !default;
$mdlapp-color-accent: "3,169,244"   !default;
$mdlapp-color-accent-contrast: "255,255,255" !default;
```
Override MDL SASS variables
```sass
/* ==========  Color & Themes  ========== */
$color-primary: $mdlapp-color-primary;
$color-primary-dark: $mdlapp-color-primary-dark;
$color-accent: $mdlapp-color-accent;
$color-primary-contrast: $mdlapp-color-primary-contrast;
$color-accent-contrast: $mdlapp-color-accent-contrast;

/* ==========  Typography  ========== */
$text-color-primary: unquote("rgba(#{$mdlapp-text-color-primary}, 0.87)");
$text-link-color: unquote("rgb(#{$color-accent})");
```

**Comment by markopaju** [comment]
Not really what i was asking for.
But here's what i actually mean:

`//all colors
$color-palettes: (
  'red': $palette-red,
  'pink': $palette-pink,
  'purple': $palette-purple,
  'deep-purple': $palette-deep-purple,
  'indigo': $palette-indigo,
  'blue': $palette-blue,
  'light-blue': $palette-light-blue,
  'cyan': $palette-cyan,
  'teal': $palette-teal,
  'green': $palette-green,
  'light-green': $palette-light-green,
  'lime': $palette-lime,
  'yellow': $palette-yellow,
  'amber': $palette-amber,
  'orange': $palette-orange,
  'deep-orange': $palette-deep-orange,
  'brown': $palette-brown,
  'grey': $palette-grey,
  'blue-grey': $palette-blue-grey
);
//color variations
$color-orders: 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, A100, A200, A400, A700;
//primary palette
$primary-palette: map-get($color-palettes, 'indigo');
//ascent palette
$accent-palette: map-get($color-palettes, 'pink');

//generate all color palettes
@each $name, $value in $color-palettes {
  @for $i from 1 through length($value) {
    .mdl-color--#{$name}-#{nth($color-orders, $i)} {
      background-color: nth($value, $i) !important;
    }

    .mdl-color-text--#{$name}-#{nth($color-orders, $i)} {
      color: nth($value, $i) !important;
    }

    .mdl-color-border--#{$name}-#{nth($color-orders, $i)} {
      border-color: nth($value, $i) !important;
    }
  }
}

//generate primary palettes
@for $i from 1 through length($color-orders) {
  .mdl-color--primary-#{nth($color-orders, $i)} {
    background-color: nth($primary-palette, $i) !important;
  }

  .mdl-color-text--primary-#{nth($color-orders, $i)} {
    color: nth($primary-palette, $i) !important;
  }

  .mdl-color-border--primary-#{nth($color-orders, $i)} {
    border-color: nth($primary-palette, $i) !important;
  }
}

//generate ascent palettes
@for $i from 1 through length($color-orders) {
  .mdl-color--accent-#{nth($color-orders, $i)} {
    background-color: nth($accent-palette, $i) !important;
  }

  .mdl-color-text--accent-#{nth($color-orders, $i)} {
    color: nth($accent-palette, $i) !important;
  }

  .mdl-color-border--accent-#{nth($color-orders, $i)} {
    border-color: nth($accent-palette, $i) !important;
  }
}`

**Comment by markopaju** [comment]
I actually meant something like this:

```css
/* ==========  Variables  ========== */
$color-palettes: (
  'red': $palette-red,
  'pink': $palette-pink,
  'purple': $palette-purple,
  'deep-purple': $palette-deep-purple,
  'indigo': $palette-indigo,
  'blue': $palette-blue,
  'light-blue': $palette-light-blue,
  'cyan': $palette-cyan,
  'teal': $palette-teal,
  'green': $palette-green,
  'light-green': $palette-light-green,
  'lime': $palette-lime,
  'yellow': $palette-yellow,
  'amber': $palette-amber,
  'orange': $palette-orange,
  'deep-orange': $palette-deep-orange,
  'brown': $palette-brown,
  'grey': $palette-grey,
  'blue-grey': $palette-blue-grey
);

$color-orders: 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, A100, A200, A400, A700;

$primary-palette: map-get($color-palettes, 'indigo');
$accent-palette: map-get($color-palettes, 'pink');

/* ==========  Palettes  ========== */
@each $name, $value in $color-palettes {
  @for $i from 1 through length($value) {
    .mdl-color--#{$name}-#{nth($color-orders, $i)} {
      background-color: nth($value, $i) !important;
    }

    .mdl-color-text--#{$name}-#{nth($color-orders, $i)} {
      color: nth($value, $i) !important;
    }

    .mdl-color-border--#{$name}-#{nth($color-orders, $i)} {
      border-color: nth($value, $i) !important;
    }
  }
}

@for $i from 1 through length($color-orders) {
  .mdl-color--primary-#{nth($color-orders, $i)} {
    background-color: nth($primary-palette, $i) !important;
  }

  .mdl-color-text--primary-#{nth($color-orders, $i)} {
    color: nth($primary-palette, $i) !important;
  }

  .mdl-color-border--primary-#{nth($color-orders, $i)} {
    border-color: nth($primary-palette, $i) !important;
  }
}

@for $i from 1 through length($color-orders) {
  .mdl-color--accent-#{nth($color-orders, $i)} {
    background-color: nth($accent-palette, $i) !important;
  }

  .mdl-color-text--accent-#{nth($color-orders, $i)} {
    color: nth($accent-palette, $i) !important;
  }

  .mdl-color-border--accent-#{nth($color-orders, $i)} {
    border-color: nth($accent-palette, $i) !important;
  }
}
```
