### ISSUE TITLE
Bug: Table rows borders do not renders (Chrome)

### ISSUE THREAD

**Issue by blobor** [google/material-design-lite#4325]
MDL version: 1.1.3
Browser: Chrome
Browser version: 50.0.2661.94
Operating system: Windows 
Operating system version: 6.3.9600
URL: http://codepen.io/blobor/pen/WwLVOm

Table "mdl-data-table", it's not shows borders of rows until you hover over on them.

Possible solution:
Basically we need to change border rendering from table cell to table row.

Instead:
```css
.mdl-data-table td {
    border-top: 1px solid rgba(0, 0, 0, 0.12);
    border-bottom: 1px solid rgba(0, 0, 0, 0.12);
}
```

Use this:
```css
.mdl-data-table tbody tr {
    border-top: 1px solid rgba(0, 0, 0, 0.12);
    border-bottom: 1px solid rgba(0, 0, 0, 0.12);
}
``` 

Screenshot:
![image](https://cloud.githubusercontent.com/assets/4813007/15076074/726134a6-13b0-11e6-948a-3cb7f5dcf3cd.png)
