### ISSUE TITLE
Implement Tooltip v2 Component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4495]
Spec reference: https://material.google.com/components/tooltips.html

**Comment by tleunen** [comment]
When implementing the tooltip in v2, would it be possible to not use ID to reference the element (and the tooltip)?

I don't really know what could be the best way to implement it, maybe something like this?
First child would be the tooltip content, the second child the element.
```
<div data-component="tooltip">
    <div>Tooltip content</div>
    <div>Element on which we want the tooltip to be displayed</div>
</div>
```

**Comment by traviskaufman** [comment]
I actually really like the approach described [here](https://webdesignerhut.com/pure-css-tooltips-with-html5-data-attribute/). Perhaps for our out-of-the-box use case we could use a data attribute the points to the tooltip that you want to use, and then have the tooltip look for specific attributes in preferential order, e.g. - 

* `title`
* `alt`
* `aria-label`
* ....

```html
<i class="material-icons" data-mdl-tooltip title="Save to favorites">favorite</i>
```

```css
[data-mdl-tooltip]:after {
  content: attr(aria-label);
  content: attr(alt);
  content: attr(title);
  /* other styles... */
}
```
