### ISSUE TITLE
Add enter/exit mixins to mdl-animation

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4773]
In many of our components such as checkboxes, radios, and icon toggles, we do stuff like this:

```scss
.mdl-component {
  transition: opacity 120ms $mdl-animation-fast-out-linear-in-timing-function;
  opacity: 0;
}

.mdl-component--active {
  transition: opacity 120ms $mdl-animation-linear-out-slow-in-timing-function;
  opacity: 1;
}
```

This is because when something enters a frame, it should use the `linear-out-slow-in` timing function, and when it exits it should use `fast-out-linear-in`. This is not apparent by the use of the timing functions or by the names of the timing functions themselves, and therefore unintuitive to look at from a developer standpoint. It's also extremely unwieldy to write and difficult to remember, especially with multiple transforms.

I say we add some functions for `mdl-animation` to account for this:

```scss
@function mdl-animation-enter($property, $duration, $delay: 0ms) {
  @return $property $duration $delay $mdl-animation-linear-out-slow-in-timing-function;
}

@function mdl-animation-exit($property, $duration, $delay: 0ms) {
  @return $property $duration $delay $mdl-animation-fast-out-linear-in-timing-function;
}
```

That we can use like so:

```scss
.mdl-component {
  transition: mdl-animation-exit(opacity, 120ms);
  opacity: 0;
}

.mdl-component--active {
  transition: mdl-animation-enter(opacity, 120ms);
  opacity: 1;
}
```

This makes it way easier to work with multiple transition properties:

```scss
.mdl-component {
  transition: mdl-animation-exit(opacity, 120ms), mdl-animation-exit(transform, 180ms, 60ms);
}
```

It can also work with animations:

```scss
@keyframes fade-in {
  from {
    opacity: 0;
  }

  to {
    opacity: 1;
  }
}

.mdl-component--active {
  animation: mdl-animation-enter(fade-in, 120ms);
}
```

cc @sgomes @Garbee
