### ISSUE TITLE
Improve styling for CodePen examples

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#607]
When we try to use CodePen for the layout examples here's what I get:

Transparent header:

![](http://i.imgur.com/uIbIgtM.png)

Fixed drawer-no header:

![](http://i.imgur.com/gXyx5qi.png)

Fixed header:

![](http://i.imgur.com/BfU9Bu7.png)

Fixed header and drawer:

![](http://i.imgur.com/8aeiQs4.png)

In most cases the two things we need to tweak are the default `body` padding, which we might want to special case to specific examples in the CodePen implementation and there's the image referencing issue which we'll figure out separately. 

One suggestion from Sergio:

We could potentially have an extra CSS file that gets used for pushing to codepen, and would be configured in the components markdown. Something along the lines of:

``` yaml
- snippet_group:
  - caption: Transparent header
    file: transparent.html
    demo_file: transparent-demo.html
    full_width: true
    extra_codepen_css: body_reset.css
```
