### ISSUE TITLE
Make CSS URIs relative

### ISSUE THREAD

**Issue by Gheoan** [google/material-design-lite#792]
For example https://github.com/google/material-design-lite/blob/master/src/checkbox/_checkbox.scss#L120
```css
{
mask: url("/images/tick-mask.svg?embed");
}
```
should be
```css
{
mask: url("images/tick-mask.svg?embed");
}
```
