### ISSUE TITLE
Spacing unit?

### ISSUE THREAD

**Issue by OliverJAsh** [google/material-design-lite#810]
For example, when I have two radio buttons:

![image](https://cloud.githubusercontent.com/assets/921609/8547515/5394d688-24b7-11e5-8cb5-0365e8c1107e.png)

What would be the correct unit of spacing to separate this two buttons along a horizontal axis?

I'm currently forcing this:

``` css
.mdl-radio {
    margin-left: 1.5rem;
}

.mdl-radio:first-child {
    margin-left: 0;
}
```

**Comment by Garbee** [comment]
There is no specified spacing for radio controls. What I would do is flexbox to align them evenly throughout the container. However you want to display them seems fine unless another spec relates to this display style (which I have yet to make the connection between.)

**Comment by kitgrose** [comment]
It's no answer to your question ([the element spacing page in the spec][1] is very quiet on horizontal spacing generally), but in terms of CSS, you can do what you're describing with a single selector provided the radio elements are siblings, using [the adjacent sibling selector][2]:

````css
.mdl-radio + .mdl-radio {
    margin-left: 1.5rem;
}
````

  [1]: https://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-keylines-spacing
  [2]: https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_selectors
